views/vk_utils.py
# coding=utf-8

"""
Copyright © 2016, Matvey Vyalkov

This file is part of SysRq tools4lulz.
SysRq tools4lulz is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SysRq tools4lulz is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with SysRq tools4lulz.  If not, see <http://www.gnu.org/licenses/>.
"""

import requests
from flask import Blueprint, render_template, request, url_for

try:
    from ..modules import general
    from ..modules import vk_utils
except ValueError:
    from modules import general
    from modules import vk_utils

vk_view = Blueprint('vk', __name__)


@vk_view.route('/resolve')
def resolve_page():
    return render_template("vk/resolve.html")


@vk_view.route('/resolve/result', methods=["POST"])
def resolve_result():
    link = request.form["link"]
    wall = general.resolve(link)
    if wall["type"] in ["group", "page"]:
        return "[club{id}|{title}]".format(**wall)
    else:
        return "[id{id}|{title}]".format(**wall)


@vk_view.route('/anticheat/oauth')
def anticheat_oauth():
    data = requests.get("https://oauth.vk.com/access_token?client_id=5489908" +
                        "&client_secret=l4Hn8Rs2lLn754kxm93h" +
                        "&redirect_uri=" + url_for("vk.anticheat_oauth", _external=True) +
                        "&code=" + request.args["code"]).json()
    token = data["access_token"]
    return render_template("vk/anticheat/set_token.html", token=token)


@vk_view.route('/anticheat/results', methods=["POST"])
def anticheat_results():
    link = request.form["link"]
    token = request.form["token"]
    return render_template("vk/anticheat/chart.html",
                           **vk_utils.anticheat(link, token))


@vk_view.route('/anticheat')
def anticheat():
    return render_template("vk/anticheat/index.html")

templates/vk/anticheat/chart.html
<html>
<head>
    <meta charset="utf-8" />
    <link rel="icon" sizes="192x192" href="/img/favicon.png">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {packages: ['corechart'], language: 'ru'})
        google.charts.setOnLoadCallback(drawChart)
        
        function drawChart() {
            var options = {
                title: 'Голоса только от участников',
                animation: {"startup": true}
            }
            var data = new google.visualization.DataTable()
            var chart = new google.visualization.BarChart(document.getElementById('anticheat'))
            data.addColumn('string', 'Вариант')
            data.addColumn('number', 'Голоса')
            data.addColumn({type: 'string',
                            role: 'annotation'})
            data.addRows({{ data|safe }})

            chart.draw(data, options)
        }
        localStorage.removeItem("token")
    </script>
    <title>Анти-накрутка</title>
</head>
<body>
    <div id="anticheat" style="width: 100%; height: {{height}}px;"></div>
</body>
</html>

templates/vk/anticheat/index.html
<html>
<head>
    <meta charset="utf-8" />
    <title>Анти-накрутка</title>
    <link rel="stylesheet" href="/css/main.css" />
    <link rel="icon" sizes="192x192" href="/img/favicon.png">
    <script type="text/javascript">
        if (!localStorage.getItem("token")) {
            window.location.replace("https://oauth.vk.com/authorize?client_id=5489908&display=page" +
                                    "&redirect_uri=" + {{ url_for("vk.anticheat_oauth", _external=True)|tojson }} +
                                    "&scope=wall,groups,offline&response_type=code&v=5.53")
        }
    </script>
</head>
<body>
    <div class="container">
        <form action="/vk/anticheat/results" method="post" target="_blank">
            <table>
                <tbody>
                    <h3>Анти-накрутка</h3>
                </tbody>
                <tr>
                    <div class="row uniform">
                        <div class="6u 12u(xsmall)">
                            <input name="link" type="text" id="link" placeholder="Ссылка" />
                        </div>
                        <input type="hidden" name="token" id="token" value="">
                    </div>
                </tr><tr>
                    <div class="row uniform">
                        <div class="12u">
                            <input value="Просмотр" class="special" type="submit" />
                        </div>
                    </div>
                </tr>
            </table>
        </form>
        <center>
            <h6>Создано для паблика <a href="https://vk.com/hispolgolos" target="_blank">Историко-политические голосования</a></h6>
        </center>
    </div>
    <script>
        document.getElementById("token").value = localStorage.getItem("token")
    </script>
</body>
</html>

templates/vk/anticheat/set_token.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Переадресация...</title>
    <script>
        localStorage.setItem("token", {{ token|tojson }})
        window.location.replace({{ url_for("vk.anticheat", _external=True)|tojson }})
    </script>
</head>
<body>
</body>
</html>